export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_MESSAGE = "SET_MESSAGE";

export const INCREASE = "SET_INCREASE";
export const DECREASE = "SET_DECRESE";

export const GET_ALL_SUBSCRIBERS = "GET_ALL_SUBSCRIBERS";
export const GET_ONE_SUBSCRIBER = "GET_ONE_SUBSCRIBER";
export const DELETE_ONE_SUBSCRIBER = "DELETE_ONE_SUBSCRIBER";
export const UPDATE_ONE_SUBSCRIBER = "UPDATE_ONE_SUBSCRIBER";
export const CREATE_ONE_SUBSCRIBER = "CREATE_ONE_SUBSCRIBER";
export const SUBSCRIBER_LOADING = "SUBSCRIBER_LOADING";
export const SUBSCRIBER_LOADING_OFF = "SUBSCRIBER_LOADING_OFF";
export const RESET_SUBSCRIBER_DATA = "RESET_SUBSCRIBER_DATA";
